- apis/filesystem/src/test/java/org/jclouds/filesystem/predicates/validators/internal/FilesystemContainerNameValidatorTest.java
previoisly it was testing blob key validator instead of container
name validator
> fix fs container validator test

- blobstore/src/main/java/org/jclouds/blobstore/BlobStore.java
blobMetadata and getBlob return null when a blob does not exist and
callers should check for this.
> Add @Nullable attribute to BlobStore methods

- apis/s3/src/main/java/org/jclouds/s3/S3ApiMetadata.java
- apis/s3/src/test/java/org/jclouds/s3/PathBasedS3ClientExpectTest.java
- apis/s3/src/test/java/org/jclouds/s3/S3ClientExpectTest.java
- apis/s3/src/test/java/org/jclouds/s3/binders/BindAsHostPrefixIfConfiguredNoPathTest.java
- apis/s3/src/test/java/org/jclouds/s3/blobstore/S3BlobSignerExpectTest.java
- apis/s3/src/test/java/org/jclouds/s3/filters/RequestAuthorizeSignatureTest.java
- providers/aws-s3/src/main/java/org/jclouds/aws/s3/AWSS3ApiMetadata.java
This prevents users from accidentally connecting to AWS.
> JCLOUDS-794: Use bogus URL for generic S3 endpoint

- apis/atmos/src/main/java/org/jclouds/atmos/AtmosClient.java
- apis/atmos/src/main/java/org/jclouds/atmos/blobstore/AtmosBlobStore.java
- apis/atmos/src/main/java/org/jclouds/atmos/filters/SignRequest.java
- apis/atmos/src/main/java/org/jclouds/atmos/options/PutOptions.java
- apis/filesystem/src/test/java/org/jclouds/filesystem/integration/FilesystemContainerIntegrationTest.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/reference/SwiftHeaders.java
- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobStore.java
- apis/s3/src/main/java/org/jclouds/s3/domain/AccessControlList.java
- apis/swift/src/main/java/org/jclouds/openstack/swift/blobstore/SwiftBlobStore.java
- apis/swift/src/test/java/org/jclouds/openstack/swift/blobstore/integration/SwiftContainerIntegrationLiveTest.java
- blobstore/src/main/java/org/jclouds/blobstore/BlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/domain/ContainerAccess.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/TransientContainerIntegrationTest.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
Implement setting and getting container ACL for public read and private access.  Tested against Atmos Online, AWS-S3, Microsoft Azure, and Rackspace CloudFiles.
> JCLOUDS-660: Improve container ACL support

- apis/atmos/src/main/java/org/jclouds/atmos/blobstore/AtmosBlobStore.java
- apis/atmos/src/test/java/org/jclouds/atmos/blobstore/integration/AtmosIntegrationLiveTest.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/functions/ParseObjectFromResponse.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobIntegrationLiveTest.java
- apis/s3/src/main/java/org/jclouds/s3/S3Client.java
- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobStore.java
- apis/s3/src/main/java/org/jclouds/s3/xml/PartIdsFromHttpResponse.java
- apis/s3/src/test/java/org/jclouds/s3/S3ClientLiveTest.java
- apis/s3/src/test/java/org/jclouds/s3/xml/PartIdsFromHttpResponseTest.java
- apis/s3/src/test/resources/multipart-upload-list-parts.xml
- apis/swift/src/main/java/org/jclouds/openstack/swift/blobstore/SwiftBlobStore.java
- apis/swift/src/test/java/org/jclouds/openstack/swift/blobstore/integration/SwiftBlobIntegrationLiveTest.java
- blobstore/pom.xml
- blobstore/src/main/java/org/jclouds/blobstore/BlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/domain/MultipartPart.java
- blobstore/src/main/java/org/jclouds/blobstore/domain/MultipartUpload.java
- blobstore/src/main/java/org/jclouds/blobstore/util/ForwardingBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/util/ReadOnlyBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
- providers/aws-s3/src/main/java/org/jclouds/aws/s3/blobstore/AWSS3BlobStore.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobClient.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
@danbroudy @kahing @timuralp @zack-shoylev Please review.  This commit exposes all the component multipart upload operations.  Unfortunately providers have different requirements for part sizes, aborting, adding metadata during initate or complete, and whether the provider offers composite objects (Swift) or merely partial uploads (S3).  I did my best here but give the new `BlobStore` methods extra scrutiny.  Still noodling over how to support this with the local blobstores but it will likely be similar to Swift.
@danbroudy @zack-shoylev I would appreciate your help with GCS and Swift, respectively.  I took a whack at the latter but it needs some more work around part sizes.
> JCLOUDS-894: Expose multipart upload component operations

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobStoreIntegrationTest.java
for range get in a LocalBlobStore, metadata.getSize() has the
original blob size and contentMetadata.getContentLength() has
the actual payload size. Other blobstores have the same size
in both
> metadata and content metadata should have the same length

- blobstore/src/main/java/org/jclouds/blobstore/TransientStorageStrategy.java
container may not be valid hostnames and the current blob uri
code can fail. there isn't really a way to use uri for transient
blobstore anyway, and removing it is the easier option. for
reference, filesystem blobstore also doesn't do this
> remove blob uri from transient blobstore

- resources/checkstyle.xml
Google Auto provides some shaded dependencies, such as Guava, that should not be directly imported. This pull request sets a checkstyle rule to make sure we don't add them by mistake.
> Avoid AutoValue shaded imports

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/domain/SwiftObject.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
swift doesn't return the etag if the client is doing a range
get of a manifest (SLO or DLO), this fixes SwiftObject so
etag is optional
> fix range get for manifest object

- apis/openstack-swift/pom.xml
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobIntegrationLiveTest.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobSignerLiveTest.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftContainerIntegrationLiveTest.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobSignerLiveTest.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobStoreIntegrationTest.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
This allows setting to zero for strongly-consistency implementations
of s3 and swift stores.
> Use a configurable timeout for awaitConsistency

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
This is related with #776. It's necessary to add
the 'bytes' string before the bytes.
> Add missing value in Content-Range header

- apis/filesystem/src/test/java/org/jclouds/filesystem/FilesystemBlobStoreTest.java
Fix a regression in the file system blob store, where a test does not
expect the trailing delimiter character.
> JCLOUDS-930: Regression in a File System test.

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/strategy/internal/ListContainerTest.java
We should not append a "/" to the marker when returning list results
in the case of directories (RELATIVE_PATH), as the names will already
include the delimiter.
Added a jclouds test to catch such regressions in the local store in
the future.
> JCLOUDS-930: LocalBlobStore -- marker regression.

- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerLiveTest.java
Relaxes the membership check in prefix testing. The check is no longer
sensitive to ordering of the results, as different providers may
append, prepend, or insert in sorted order the relative prefixes.
> Relax membership assertion for the prefix test.

- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/functions/ListBlobsResponseToResourceList.java
- providers/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/domain/UrlMapValidateResult.java
Multiple constructors annotated with `@SerializedNames` confuses
`NamingStrategies.translateName` and causes failures with newer JDK.
Since the second constructor does not need this annotation we remote
it.
> JCLOUDS-857: remove spurious annotation

- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/functions/ListBlobsResponseToResourceList.java
We should not filter out prefixes when listing containers, similarly
to the way swift behaves. This makes the marker blobs apparently to
the user.
> Azure Blob: do not filter out prefixes.

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
This avoids `OutOfMemoryError` with large blobs and resolves issues with
ranges exceeding array limits.
> Do not buffer range get in LocalBlobStore

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- core/pom.xml
This may resolve issues with older versions of Maven.  Release notes:
https://sites.google.com/site/gson/gson-roadmap
> JCLOUDS-974: Upgrade to GSON 2.3.1

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/features/ObjectApi.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/reference/SwiftHeaders.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobIntegrationLiveTest.java
Previously Swift copy would append metadata instead of replacing it.
> JCLOUDS-883: Replace metadata during Swift copy

- providers/rackspace-cloudfiles-uk/src/test/java/org/jclouds/rackspace/cloudfiles/uk/features/CloudFilesUKObjectApiLiveTest.java
- providers/rackspace-cloudfiles-us/src/test/java/org/jclouds/rackspace/cloudfiles/us/features/CloudFilesUSObjectApiLiveTest.java
> Subclass ObjectApiLiveTest in Cloudfiles providers

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/features/ObjectApi.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/features/ObjectApiLiveTest.java
The existing method replaces metadata.
> JCLOUDS-872: Swift copy object and append metadata

- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
Azure does not allow arbitrary marker specification and the generic
testListContainerMarker test should not assume that the behavior is
possible. There is already a separate test for such scenario that is
skipped on Azure.
> Remove last marker test from ListContainerMarker.

- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/integration/AzureBlobIntegrationLiveTest.java
Azure ```testGetRange()``` has been consistently failing for a while. Disable the test until it is fixed.
> Skip broken Azure Blob test.

- apis/cloudstack/src/test/java/org/jclouds/cloudstack/compute/CloudStackComputeServiceAdapterExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/compute/extensions/CloudStackImageExtensionExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/compute/extensions/CloudStackSecurityGroupExtensionExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/FirewallApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/GlobalHostApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/GlobalUserApiTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/GlobalZoneApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/ISOApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/SecurityGroupApiTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/SnapshotApiTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/TagApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/TemplateApiTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/VirtualMachineApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/ZoneApiExpectTest.java
- apis/cloudstack/src/test/java/org/jclouds/cloudstack/internal/BaseCloudStackComputeServiceContextExpectTest.java
- apis/swift/src/main/java/org/jclouds/openstack/swift/functions/ParseObjectInfoListFromJsonResponse.java
- core/src/main/java/org/jclouds/http/Uris.java
- core/src/main/java/org/jclouds/util/Strings2.java
- core/src/test/java/org/jclouds/http/HttpRequestTest.java
- core/src/test/java/org/jclouds/util/Strings2Test.java
- providers/aws-s3/src/main/java/org/jclouds/aws/s3/blobstore/AWSS3BlobRequestSigner.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/AWSS3BlobSignerExpectTest.java
This PR removes the decoding multi map from URI and makes changes primarily to tests to not work around its behavior. This does not fix an existing issue, but I believe it simplifies the internals of handling parameters in jclouds.
Background
-----------------
Currently, calling ```addQueryParam()``` when constructing an HttpRequest results in inserting the key and the value into a decoding MultiMap. What it means is that the parameter value is decoded prior to being inserted and then encoded again on retrieval.
Further, there is some additional logic that checks whether a string is encoded or not in the ```Strings2.urlDecode()``` method. This behavior is also problematic such that providers need to make sure they encode strings before adding them as a query parameter, as they may not get …
> JCLOUDS-217: do not double decode strings.

- core/src/main/java/org/jclouds/Constants.java
- core/src/main/java/org/jclouds/apis/internal/BaseApiMetadata.java
- core/src/main/java/org/jclouds/http/filters/ConnectionCloseHeader.java
- core/src/main/java/org/jclouds/rest/internal/RestAnnotationProcessor.java
- core/src/test/java/org/jclouds/http/filters/ConnectionCloseHeaderTest.java
- core/src/test/java/org/jclouds/rest/internal/RestAnnotationProcessorTest.java
Some providers do not properly support persistent connections. See: 
https://github.com/docker/docker/issues/12845
https://github.com/docker/compose/pull/1374
This pull request introduces the `jclouds.connection-close-header` property to automatically add the `Connection: close` header to all requests. This is particularly useful when using drivers that reuse connections by default (such as the [OkHttp driver](https://github.com/square/okhttp/wiki/Connections)), but still allows to configure the header explicitly in concrete methods of concrete APIs where needed.
/cc @kwart
> Allow to globally configure the 'Connection: close' header

- core/src/main/java/org/jclouds/rest/RateLimitExceededException.java
- core/src/main/java/org/jclouds/util/Throwables2.java
Added the `RateLimitExceededException` as a propagable exception. This will allow providers dealing with the service rate limits to propagate a meaningful error. Related to [JCLOUDS-1022](https://issues.apache.org/jira/browse/JCLOUDS-1022).
> Added RateLimit exception

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
Swift implements multi-part upload with user-visible parts and an
explicit manifest.  When deleting an MPU blob it can delete only the
manifest or both the manifest and parts.  For consistency with other
providers, we now do the latter in the portable abstraction.  Swift
ignores the multipart-manifest=delete parameter for single-part
objects.  Fixes andrewgaul/s3proxy#92.
> Delete parts when removing Swift multipart objects

- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
the filesystem blob store was always removing a/ when a/b was
removed, even if the client explicitly created a/. this patch
fixes that
> don't remove directory if it's a blob

- allblobstore/pom.xml
JIRA: https://issues.apache.org/jira/browse/JCLOUDS-1045
The [JCLOUDS-786](https://issues.apache.org/jira/browse/JCLOUDS-786) removed swift api, but it's still used as dependency in the `allblobstore` module.
> JCLOUDS-1045 remove swift dependency from allblobstore module

- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
Test shows that the bucket access supersedes the blob access policy.
> JCLOUDS-1042: Remove unneeded ACL swizzling

- apis/s3/src/main/java/org/jclouds/s3/S3Client.java
- apis/s3/src/main/java/org/jclouds/s3/binders/BindCannedAclToRequest.java
- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobStore.java
- apis/s3/src/test/java/org/jclouds/s3/S3ClientLiveTest.java
- apis/s3/src/test/java/org/jclouds/s3/S3ClientTest.java
These are simpler than the full XML API and better supported by
non-AWS S3 implementations, e.g., Ceph, S3Proxy.
> Use canned ACLs with S3

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
At the moment, `AzureBlobStore.getBlobAccess` throws `UnsupportedOperationException`. I have implemented this. Please refer to this [issue](https://github.com/andrewgaul/s3proxy/issues/111) for details. @andrewgaul Please review.
> Add support for AzureBlobStore.getBlobAccess

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
@andrewgaul Use parseLong instead of parseInt when parsing open-ended byte ranges in LocalBlobStore. Without this fix, any "from byte x to end" or "from beginning to byte x" getBlob() call will throw a NumberFormatException if x is too big to fit into an int (2 GB).
Fixes https://issues.apache.org/jira/browse/JCLOUDS-1073
> Use parseLong instead of parseInt in range parser

- drivers/okhttp/src/main/java/org/jclouds/http/okhttp/OkHttpCommandExecutorService.java
- drivers/okhttp/src/test/java/org/jclouds/http/okhttp/OkHttpCommandExecutorServiceTest.java
https://issues.apache.org/jira/browse/JCLOUDS-1091
> JCLOUDS-1091: Populate the Content-Length header in the OkHttp driver

- apis/elasticstack/src/main/java/org/jclouds/elasticstack/domain/Server.java
- apis/elasticstack/src/main/java/org/jclouds/elasticstack/domain/ServerMetrics.java
- compute/src/main/java/org/jclouds/compute/domain/internal/HardwareImpl.java
- compute/src/main/java/org/jclouds/compute/internal/BaseComputeService.java
- compute/src/main/java/org/jclouds/ovf/internal/BaseEnvelope.java
- compute/src/main/java/org/jclouds/ovf/internal/BaseVirtualSystem.java
- compute/src/test/java/org/jclouds/compute/internal/BaseComputeServiceLiveTest.java
- core/src/main/java/org/jclouds/json/internal/NamingStrategies.java
- loadbalancer/src/main/java/org/jclouds/loadbalancer/internal/BaseLoadBalancerService.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/compute/suppliers/AWSEC2ImageSupplier.java
Always incorrect but previously broken on Java 9.  Reference:
https://bugs.openjdk.java.net/browse/JDK-8075793
> JCLOUDS-1101: Correct generics wildcard errors

- core/src/main/java/org/jclouds/http/UriTemplates.java
- core/src/test/java/org/jclouds/http/UriTemplatesTest.java
This allows replacement of JSON-like payloads without using hacks like
percent-encoding braces.
> Handle nested braces in UriTemplates.expand

- compute/src/test/java/org/jclouds/compute/StubComputeServiceIntegrationTest.java
- compute/src/test/java/org/jclouds/compute/internal/BaseComputeServiceLiveTest.java
Extract the task cancellation to a specific test so it does not prevent other tests from running if it fails.
> Isolate the task cancellation in a test

- compute/src/main/java/org/jclouds/compute/callables/SudoAwareInitManager.java
- compute/src/main/java/org/jclouds/ssh/SshClient.java
- drivers/jsch/src/main/java/org/jclouds/ssh/jsch/JschSshClient.java
- drivers/jsch/src/test/java/org/jclouds/ssh/jsch/JschSshClientLiveTest.java
- drivers/sshj/src/main/java/org/jclouds/sshj/SshjSshClient.java
- drivers/sshj/src/test/java/org/jclouds/sshj/SshjSshClientLiveTest.java
The `refreshAndRunAction` is called by the `future.cancel()` method when cancelling the future associated to a running script (typically obtained by calling the `compute.submitScriptOnNode` method.
I've observed that when the ssh connection is already established, this method fails to connect again and throws an exception. This was also causing random failures in the `BaseComputeServiceLiveTest.testWeCanCancelTasks`.
@devcsrj This will potentially fix [JCLOUDS-1058](https://issues.apache.org/jira/browse/JCLOUDS-1058). Could you build this branch and try running the tests?
> Do not try to connect to ssh if already connected

- apis/docker/src/test/java/org/jclouds/docker/features/ImageApiLiveTest.java
- apis/rackspace-cloudfiles/src/test/java/org/jclouds/rackspace/cloudfiles/v1/options/UpdateCDNContainerOptionsTest.java
- common/googlecloud/src/main/java/org/jclouds/googlecloud/internal/ListPages.java
- core/src/main/java/org/jclouds/ContextBuilder.java
- core/src/main/java/org/jclouds/apis/ApiPredicates.java
- core/src/main/java/org/jclouds/apis/Apis.java
- core/src/main/java/org/jclouds/internal/BaseView.java
- core/src/main/java/org/jclouds/providers/ProviderPredicates.java
- core/src/main/java/org/jclouds/rest/InputParamValidator.java
- core/src/main/java/org/jclouds/util/TypeTokenUtils.java
- core/src/test/java/org/jclouds/internal/BaseViewTest.java
- providers/aws-ec2/src/test/java/org/jclouds/aws/ec2/features/PlacementGroupApiLiveTest.java
- providers/softlayer/src/test/java/org/jclouds/softlayer/features/VirtualGuestApiLiveTest.java
JCLOUDS-1074: Guava 20 compatibility
* dynamically call TypeToken.isSupertypeOf with Guava 19 and later and
TypeToken.isAssignableFrom with Guava 18 and earlier
* consume or ignore values from methods with CheckReturnValue
* replace usage of removed Iterators.emptyIterator
> JCLOUDS-1074: Guava 20 compatibility

- apis/atmos/src/test/java/org/jclouds/atmos/blobstore/integration/AtmosContainerIntegrationLiveTest.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/integration/AzureBlobContainerIntegrationLiveTest.java
Previously using prefix markers would not correctly find the next key.
Add test for this behavior.
> JCLOUDS-945: fix local blobstore marker handling

- apis/ec2/src/test/java/org/jclouds/ec2/compute/extensions/EC2ImageExtensionLiveTest.java
- compute/src/test/java/org/jclouds/compute/extensions/internal/BaseImageExtensionLiveTest.java
- compute/src/test/java/org/jclouds/compute/internal/BaseComputeServiceLiveTest.java
- providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/domain/Action.java
* Improves the test order in the `BaseComputeServiceLiveTest` to avoid skipping so many tests when the first ones fail due to SSH connection failures.
* Improves the `BaseImageExtensionLiveTest` to let subclasses properly configure custom templates.
* Fixes the DigitalOcean2 live tests.
/cc @andreaturli
> Fix base compute service live tests

- scriptbuilder/src/main/java/org/jclouds/scriptbuilder/functionloader/osgi/BundleFunctionLoader.java
Switched from Properties to HashMap to fix compilation issues. Where
Properties is not of type Dictionary<String, ?>. This passes the right
type to bundleContext.registerService. Also corrects the first argument,
String -> String[], same issue wrong type passed.
This was need to allow it to build, I created a patch for the 
[Gentoo ebuild](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/dev-java/jclouds-scriptbuilder)
> org/jclouds/scriptbuilder/functionloader/osgi/BundleFunctionLoader.java:

- core/pom.xml
- core/src/test/java/org/jclouds/osgi/BundlesTest.java
- core/src/test/java/org/jclouds/osgi/MetadataBundleListenerTest.java
- project/pom.xml
- resources/modernizer_exclusions.txt
- scriptbuilder/pom.xml
- scriptbuilder/src/main/java/org/jclouds/scriptbuilder/functionloader/osgi/BundleFunctionLoader.java
This is based on https://github.com/jclouds/jclouds/pull/1033.
This PR fixes the build of the previous one and makes the OSGi framework version configurable, so we can run builds for different environments. The scope of the OSGi dependencies is `provided`, so we can expect target platforms to have different versions than the ones used to build jclouds.
With this change, the build succeeds with the base version, and also with the latest versions:
mvn clean install -Dosgi.version=6.0.0 -Dosgi.compendium.version=5.0.0
> Make jclouds compatible with newer OSGi framework versions

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStoreParallelLiveTest.java
This avoids creating junk in the source directory.
> Use temporary file for Swift test inputs

- providers/azureblob/pom.xml
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobApiMetadata.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/AzureBlobRequestSignerTest.java
This raises the maximum multipart size from 195 GB to 4.77 TB.
Reference:
https://azure.microsoft.com/en-us/blog/general-availability-larger-block-blobs-in-azure-storage/
> JCLOUDS-1223: Use larger block blobs for Azure

- apis/s3/src/main/java/org/jclouds/s3/S3Client.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/AWSS3ClientExpectTest.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/AWSS3ClientTest.java
When making a `GetBucketLocation` request, Amazon may route the request
to the bucket region. When making it with v4 signer, the request may
fail because of the region mismatch. Concretely, a request to
test.s3.amazonaws.com may resolve to s3-us-west-2-w.amazonaws.com. The
request itself is prepared for the us-east-1 region (s3.amazonaws.com
endpoint), but then fails when the DNS resolution points to a
us-west-2 endpoint.
Bucket-in-path works around this for the `GetBucketLocation` requests.
That means that every `GetBucketLocation` request will be of the form:
https://s3.amazonaws.com/{bucket}?location. This ensures that jclouds
requests will not be subjected to Amazon's routing/DNS pointers.
Fixes: JCLOUDS-1213
> GetBucketLocation should use path-style requests.

- core/src/main/java/org/jclouds/functions/ExpandProperties.java
Previously Android choked on this incomplete regex.
> Correct regex in ExpandProperties

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
Add Locale.ENGLISH parameter to String.format(...) to generate same uploadId for different locales.
> JCLOUDS-1297: Fix uploadId format for non-English locale

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/functions/ParseObjectListFromResponse.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
`uriBuilder.appendPath` assumes an encoded path.
> JCLOUDS-1299: Handle % in names during Swift list

- providers/b2/src/main/java/org/jclouds/b2/blobstore/B2BlobStore.java
- providers/b2/src/main/java/org/jclouds/b2/domain/Action.java
- providers/b2/src/main/java/org/jclouds/b2/domain/B2ObjectList.java
- providers/b2/src/main/java/org/jclouds/b2/features/ObjectApi.java
- providers/b2/src/test/java/org/jclouds/b2/features/ObjectApiLiveTest.java
- providers/b2/src/test/java/org/jclouds/b2/features/ObjectApiMockTest.java
Previously B2 emulated prefix and delimiter via client-side filtering.
Enabled by recent service additions.
> JCLOUDS-1304: B2 native prefix and delimiter

- core/src/main/java/org/jclouds/rest/config/CredentialStoreModule.java
- core/src/test/java/org/jclouds/rest/CredentialStoreModuleTest.java
With a shared credential store the configuration of one compute service leaks in all others, causing the wrong credentials to be used when not overridden.
The particular problem this fixes - [Azure sets default username/password for images](https://github.com/jclouds/jclouds-labs/blob/master/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/AzureComputeProviderMetadata.java#L98) which leaks to other providers (through [GetLoginForProviderFromPropertiesAndStoreCredentialsOrReturnNull](https://github.com/jclouds/jclouds/blob/master/compute/src/main/java/org/jclouds/compute/config/GetLoginForProviderFromPropertiesAndStoreCredentialsOrReturnNull.java#L51)), causing the wrong username/password to be used.
Even if the credentials are scoped to a specific provider in the map, it still …
> JCLOUDS-1321: Use separate credential stores per context

- core/src/main/java/org/jclouds/http/functions/ParseXMLWithJAXB.java
- core/src/main/java/org/jclouds/xml/internal/JAXBParser.java
- core/src/test/java/org/jclouds/rest/binders/BindToXMLPayloadTest.java
This caused failures to parse Azure Queue Storage list requests.
> JCLOUDS-1325: Ignore Unicode BOM in XML parser

- core/src/main/java/org/jclouds/util/Passwords.java
- core/src/test/java/org/jclouds/util/PasswordsTest.java
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/compute/ProfitBricksComputeServiceAdapter.java
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/util/Preconditions.java
As discussed in https://github.com/jclouds/jclouds-labs/pull/402
> Move Passwords implementation to jclouds-core to be reused by providers

- providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/GoogleCloudStorageApiMetadata.java
- providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/config/GoogleCloudStorageHttpApiModule.java
- providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/handlers/GoogleCloudStorageClientErrorRetryHandler.java
This addresses `rateLimitExceeded` errors encountered during integration
tests.
> Handle HTTP 429 in google-cloud-storage

- core/src/main/java/org/jclouds/util/Passwords.java
- core/src/test/java/org/jclouds/util/PasswordsTest.java
Avoids bugs where tests succeed with an average sized password but fail when the password length is at the allowed extremes.
> Generate fixed length passwords

- apis/docker/pom.xml
- apis/rackspace-cloudfiles/pom.xml
- project/pom.xml
- providers/digitalocean2/pom.xml
- providers/google-cloud-storage/pom.xml
- providers/google-compute-engine/pom.xml
- providers/packet/pom.xml
- providers/profitbricks/pom.xml
- providers/rackspace-cloudfiles-uk/pom.xml
- providers/rackspace-cloudfiles-us/pom.xml
This makes dependencies consistent and eliminates warnings of the
form:
```
$M2_HOME/repository/org/apache/jclouds/driver/jclouds-slf4j/2.1.0-SNAPSHOT/jclouds-slf4j-2.1.0-SNAPSHOT.jar(org/jclouds/logging/slf4j/config/SLF4JLoggingModule.class): warning: Cannot find annotation method 'value()' in type 'AutoService': class file for com.google.auto.service.AutoService not found
```
Reference:
https://github.com/google/auto/tree/master/service#download
> Upgrade auto-service to 1.0rc3 and make dependency optional

- apis/openstack-keystone/src/main/java/org/jclouds/openstack/keystone/v2_0/binders/BindAuthToJsonPayload.java
- apis/openstack-keystone/src/main/java/org/jclouds/openstack/keystone/v2_0/options/CreateTenantOptions.java
- apis/openstack-keystone/src/main/java/org/jclouds/openstack/keystone/v2_0/options/CreateUserOptions.java
- apis/openstack-keystone/src/main/java/org/jclouds/openstack/keystone/v2_0/options/UpdateTenantOptions.java
- apis/openstack-keystone/src/main/java/org/jclouds/openstack/keystone/v2_0/options/UpdateUserOptions.java
- apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/binders/BindSecurityGroupRuleToJsonPayload.java
- apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/options/CreateServerOptions.java
Newer JDK have a different resolution process, likely due to enhanced
target type inference.  Found via:
```
mvn test -Dmaven.compile.source=1.8 -Dmaven.compile.target=1.8
```
> JCLOUDS-1333: Correct JDK 1.8 method overloading

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/features/ObjectApi.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/features/ContainerApiLiveTest.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/features/ObjectApiLiveTest.java
The ContainerApiLiveTest class has tests that mostly assume that a
single test container always exists. They collide on changes to the
state of the container. Some of the tests, though, assume the
container does _not_ exist and attempt to create it and subsequently
delete it. The change in this patch makes their behavior uniform with
respect to that test container: assume it exists and if the test tries
to delete it or mutate it, delete the container and create it at the
end of the test.
The fix in ObjectApi is for the Object GET requests. Currently,
jclouds passes "format=json", which is not a supported query parameter
for object GET.
Lastly, ObjectApiLiveTest that test server-side copy should ignore the
X-Openstack-Request-ID header, as its value will change between the
two requests.
> Fixes for jclouds openstack swift tests.

- apis/sts/src/main/java/org/jclouds/aws/filters/FormSignerV4.java
The creation of a compute context for a China region failed because the `FormSignerV4` didn't allow China endpoints.
The error happens at constructor injection time when Guice is building all singleton objects. The `IllegalArgumentException` thrown there causes an infinite loop and ends up in an `OutOfMemoryexception`.
@andrewgaul @demobox Despite having only added the China suffix in this commit, I'd rather remove completely this validation, as it provides very little value. If the endpoint does not support V4 signatures, users will probably see a self-explanatory error response coming back. WDYT?
> JCLOUDS-1258: Allow China endpoints in FormSignerV4

- apis/ec2/src/main/java/org/jclouds/ec2/xml/BaseReservationHandler.java
- blobstore/src/main/java/org/jclouds/blobstore/internal/BaseBlobStore.java
- core/src/main/java/org/jclouds/http/internal/BaseHttpCommandExecutorService.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/BaseAWSReservationHandler.java
- providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/functions/BaseToPagedIterable.java
- providers/packet/src/main/java/org/jclouds/packet/functions/BaseToPagedIterable.java
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/http/parser/firewall/BaseFirewallResponseHandler.java
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/http/parser/firewall/rule/BaseFirewallRuleResponseHandler.java
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/http/parser/storage/BaseStorageResponseHandler.java
This is not meaningful since these classes cannot be instantiated.
Found via error-prone.
> Remove Inject on constructors for abstract classes

- project/pom.xml
This eliminates warnings of the form:
```
/home/gaul/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
```
> Specify jsr305

- core/src/test/java/org/jclouds/http/handlers/BackoffLimitedRetryHandlerTest.java
These often fail in our continuous integration tests.
> JCLOUDS-1340: Disable BackoffLimitedRetryHandlerTest

- project/pom.xml
This is a PR to experiment with Maven toolchains approach to let Jenkins use the right JDK to build jclouds.
Do not merge yet.
> Add Jenkins profile to use Maven toolchains

- apis/atmos/src/main/java/org/jclouds/atmos/blobstore/functions/ObjectToBlobMetadata.java
- apis/atmos/src/test/java/org/jclouds/atmos/blobstore/integration/AtmosIntegrationLiveTest.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/functions/ToBlobMetadata.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobIntegrationLiveTest.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
- providers/b2/src/main/java/org/jclouds/b2/blobstore/B2BlobStore.java
- providers/b2/src/test/java/org/jclouds/b2/blobstore/integration/B2BlobIntegrationLiveTest.java
These providers map all storage tiers to `STANDARD`.
>  JCLOUDS-1337: other putBlob portable storage tiers 

- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
When testing blobstore overwrite behavior, jclouds should use a blob
with different content (but same name).
> Use different content on overwrite.

- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
- blobstore/src/main/java/org/jclouds/blobstore/internal/BaseBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/strategy/internal/MultipartUploadSlicingAlgorithm.java
`MultipartUploadSlicingAlgorithm` creates multiple equal-sized parts and
a remaining amount.  `BaseBlobStore.putMultipartBlob` used this
interface incorrectly, which could create more parts than intended
since the remaining size could be larger than the part size.  This
manifested with Google Cloud Storage which only allows 32 parts.
> JCLOUDS-1368: Correct use of slicing algorithm

- apis/atmos/src/main/java/org/jclouds/atmos/blobstore/AtmosBlobRequestSigner.java
- apis/atmos/src/test/java/org/jclouds/atmos/blobstore/AtmosBlobRequestSignerTest.java
- apis/filesystem/src/test/java/org/jclouds/filesystem/FilesystemBlobStoreTest.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedTemporaryUrlBlobSigner.java
- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobRequestSigner.java
- blobstore/src/main/java/org/jclouds/blobstore/BlobRequestSigner.java
- blobstore/src/main/java/org/jclouds/blobstore/LocalBlobRequestSigner.java
- blobstore/src/main/java/org/jclouds/blobstore/internal/RequestSigningUnsupported.java
- blobstore/src/test/java/org/jclouds/blobstore/TransientBlobRequestSignerTest.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobSignerLiveTest.java
- blobstore/src/test/java/org/jclouds/blobstore/internal/BaseBlobSignerExpectTest.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/AWSS3BlobSignerV4ExpectTest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobRequestSigner.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/AzureBlobRequestSignerTest.java
- providers/b2/src/test/java/org/jclouds/b2/blobstore/integration/B2BlobSignerLiveTest.java
- providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/blobstore/GoogleCloudStorageBlobRequestSigner.java
- providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/blobstore/integration/GoogleCloudStorageBlobSignerLiveTest.java
Most providers never supported this functionality and the portable
abstraction should not have included it.
> JCLOUDS-1271: Remove BlobStore.signRemoveBlob

- core/src/main/java/org/jclouds/location/suppliers/all/ZoneToRegionToProviderOrJustProvider.java
- core/src/test/java/org/jclouds/location/suppliers/all/ZoneToRegionToProviderOrJustProviderTest.java
When configuring locations from properties, the `ZoneIdsSupplier` is [already filtered](https://github.com/jclouds/jclouds/blob/master/core/src/main/java/org/jclouds/location/config/LocationModule.java#L129) by the value of the `jclouds.regions` property. However, the [default implementation](https://github.com/jclouds/jclouds/blob/master/core/src/main/java/org/jclouds/location/suppliers/LocationsSupplier.java#L27) of the `LocationsSupplier` does not take that into account and returns inconsistent results: it already filters the regions according to the region filters, but always returns all the zones.
This patch adds the zone filter so all suppliers return the locations consistently.
> Consider the zone id filter in the location supplier

- providers/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/domain/DiskType.java
It looks like the zone parameter no longer comes in the responses.
> Fix GCE live tests

- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
- apis/filesystem/src/test/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImplTest.java
- blobstore/src/main/java/org/jclouds/blobstore/LocalStorageStrategy.java
- blobstore/src/main/java/org/jclouds/blobstore/TransientStorageStrategy.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
Previously `getBlobKeysInsideContainer` returned all keys and filtered
in `LocalBlobStore`.  Now `getBlobKeysInsideContainer` filters via prefix
which can dramatically decrease the number of keys returned,
especially for the filesystem provider.  Further optimizations are
possible for delimiter.
> JCLOUDS-1371: JCLOUDS-1488: list optimize prefix

- apis/sts/src/main/java/org/jclouds/aws/handlers/ParseAWSErrorFromXmlContent.java
AWS response data is encoded in UTF-8. Creating a String from said data
using the JVM's default charset results in incorrect encoding on
environments in which the JVM's default charset is not UTF-8.
https://issues.apache.org/jira/browse/JCLOUDS-1509
> JCLOUDS-1509: read AWS response data with the UTF-8 charset explicitly
