jclouds/jclouds

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
Also handle zero maxResults.  Found with Ceph s3-tests and s3proxy.
> Handle listing with marker after the last key

- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
This matches the behavior of other call sites.
Fixes andrewgaul/s3proxy#39.
> Handle null return value from File.listFiles

- providers/azureblob/pom.xml
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobApiMetadata.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureBlobMetadataToMultipartRequest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureBlobMetadataToRequest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/xml/AccountNameEnumerationResultsHandler.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/xml/ContainerNameEnumerationResultsHandler.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/AzureBlobRequestSignerTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/integration/AzureBlobIntegrationLiveTest.java
- providers/azureblob/src/test/resources/test_list_blobs.xml
- providers/azureblob/src/test/resources/test_list_blobs_options.xml
- providers/azureblob/src/test/resources/test_list_containers.xml
- providers/azureblob/src/test/resources/test_list_containers_options.xml
Also upgrade Azure API to version 2013-08-15.
> JCLOUDS-867: Azure support for Content-Disposition

- providers/azureblob/pom.xml
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobApiMetadata.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobClient.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureBlobMetadataToMultipartRequest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureBlobMetadataToRequest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/xml/AccountNameEnumerationResultsHandler.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/xml/ContainerNameEnumerationResultsHandler.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientLiveTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/AzureBlobRequestSignerTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/integration/AzureBlobIntegrationLiveTest.java
- providers/azureblob/src/test/resources/test_list_blobs.xml
- providers/azureblob/src/test/resources/test_list_blobs_options.xml
- providers/azureblob/src/test/resources/test_list_containers.xml
- providers/azureblob/src/test/resources/test_list_containers_options.xml
> Return ETag from Azure setBlobMetadata

- providers/azureblob/src/main/java/org/jclouds/azure/storage/reference/AzureStorageHeaders.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobClient.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureCopyOptionsToRequest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/options/CopyBlobOptions.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientLiveTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientTest.java
Presently lacks support for CopyBlobOptions.  API reference:
http://msdn.microsoft.com/en-us/library/dd894037.aspx
> JCLOUDS-871: Azure Copy Blob support

- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
This fixes the build in OSX based on https://github.com/jclouds/jclouds/commit/3cabb196ce62418ea497ff3087690c802f8ca7e4.
/cc @andrewgaul
> JCLOUDS-651: Fix filesystem integration tests in OSX

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobIntegrationLiveTest.java
- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobStore.java
- apis/s3/src/main/java/org/jclouds/s3/options/CopyObjectOptions.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/options/CopyOptions.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobClient.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureContentMetadataToRequest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
Add Azure, S3, and Swift variants.
> Allow overriding content metadata during copyBlob

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
Also emit this header in LocalBlobStore.
> Test for Content-Range header in single range get

- blobstore/src/main/java/org/jclouds/blobstore/domain/internal/BlobMetadataImpl.java
- blobstore/src/main/java/org/jclouds/blobstore/domain/internal/MutableBlobMetadataImpl.java
- blobstore/src/main/java/org/jclouds/blobstore/domain/internal/MutableStorageMetadataImpl.java
Possible cause of odd PageSet behavior.
> Add missing equals and hashCode methods

- apis/ec2/src/main/java/org/jclouds/ec2/xml/AttachmentHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/BaseReservationHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/BlockDeviceMappingHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/BundleTaskHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/CreateVolumeResponseHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/DescribeInstancesResponseHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/GetPasswordDataResponseHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/RunInstancesResponseHandler.java
- apis/ec2/src/main/java/org/jclouds/ec2/xml/SnapshotHandler.java
- apis/ec2/src/test/java/org/jclouds/ec2/xml/DescribeInstancesResponseHandlerTest.java
- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
- apis/openstack-nova-ec2/src/main/java/org/jclouds/openstack/nova/ec2/xml/NovaCreateVolumeResponseHandler.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/AWSDescribeInstancesResponseHandler.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/AWSRunInstancesResponseHandler.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/BaseAWSReservationHandler.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/LaunchSpecificationHandler.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/SpotHandler.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/xml/SpotInstanceHandler.java
> Fix filesystem api in OSX

- project/pom.xml
Note that this is the last version compatible with Java 6.  Changelog:
https://github.com/cbeust/testng/blob/master/CHANGES.txt
> Upgrade to testng 6.8.21

- apis/s3/src/main/java/org/jclouds/s3/predicates/validators/BucketNameValidator.java
US Standard and most S3 clones allow more bucket names than DNS
allows.
> Loosen restrictions for S3 bucket naming

- blobstore/src/main/java/org/jclouds/blobstore/domain/PageSet.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseContainerIntegrationTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/integration/AzureBlobContainerIntegrationLiveTest.java
Some providers like Azure have opaque markers.
> Do not test marker contents

- apis/s3/src/main/java/org/jclouds/s3/config/S3HttpApiModule.java
> Do not override S3 provider methods

- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobSignerLiveTest.java
Also bump expiration to a consistent 60 seconds.
> Avoid sleeping in signed URL tests

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
Due to Swift's wonky MPU implementation we must try the multi-part
delete first followed by a single-part delete if it fails.  Previously
delete would leave orphan subobjects.  Fixes andrewgaul/s3proxy#92.
> Delete single- and multi-part objects in Swift

- blobstore/src/main/java/org/jclouds/blobstore/options/ListContainerOptions.java
- core/src/main/java/org/jclouds/http/HttpResponseException.java
- core/src/main/java/org/jclouds/logging/internal/Wire.java
Superseded by prefix and delimiter support.
> JCLOUDS-1065: Deprecate inDirectory option

- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
Previously concurrent operations could expose an object before put had
completed.  Note that the temporary file is still exposed to the
client.
> Set xattr before rename to make blob create atomic

- apis/atmos/src/main/java/org/jclouds/atmos/blobstore/AtmosBlobStore.java
- apis/atmos/src/test/java/org/jclouds/atmos/blobstore/integration/AtmosIntegrationLiveTest.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/integration/SwiftBlobIntegrationLiveTest.java
- apis/s3/src/main/java/org/jclouds/s3/blobstore/S3BlobStore.java
- apis/s3/src/main/java/org/jclouds/s3/options/CopyObjectOptions.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/internal/BaseBlobStore.java
- blobstore/src/main/java/org/jclouds/blobstore/options/CopyOptions.java
- blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/integration/AWSS3BlobIntegrationLiveTest.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
This pull request changes the `CopyOptions` interface which is annotated as `@Beta`.
> JCLOUDS-651: Conditional copy blob

- core/src/main/java/org/jclouds/rest/internal/RestAnnotationProcessor.java
References jclouds/jclouds-labs#270.
> Replace identity in RestAnnotationProcessor

- apis/atmos/src/main/java/org/jclouds/atmos/AtmosApiMetadata.java
- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/SwiftApiMetadata.java
- apis/s3/src/main/java/org/jclouds/s3/S3ApiMetadata.java
- core/src/main/java/org/jclouds/Constants.java
- core/src/main/java/org/jclouds/apis/internal/BaseApiMetadata.java
- core/src/main/java/org/jclouds/http/internal/BaseHttpCommandExecutorService.java
- core/src/main/java/org/jclouds/http/internal/JavaUrlHttpCommandExecutorService.java
- core/src/test/java/org/jclouds/http/internal/BaseHttpCommandExecutorServiceTest.java
- core/src/test/java/org/jclouds/http/internal/TrackingJavaUrlHttpCommandExecutorService.java
- core/src/test/java/org/jclouds/rest/internal/BaseRestApiExpectTest.java
- drivers/apachehc/src/main/java/org/jclouds/http/apachehc/ApacheHCHttpCommandExecutorService.java
- drivers/gae/src/main/java/org/jclouds/gae/GaeHttpCommandExecutorService.java
- drivers/okhttp/src/main/java/org/jclouds/http/okhttp/OkHttpCommandExecutorService.java
- providers/dynect/src/main/java/org/jclouds/dynect/v3/config/DynECTHttpApiModule.java
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/http/ResponseStatusFromPayloadHttpCommandExecutorService.java
Enable POST for Atmos, S3, and Swift.
> JCLOUDS-1028: Configure idempotent methods

- compute/src/test/java/org/jclouds/compute/internal/BaseComputeServiceLiveTest.java
These changes are needed in https://github.com/jclouds/jclouds-labs/pull/291
/cc @ritazh
> Allow subclasses to override the scripts

- core/pom.xml
- core/src/main/java/org/jclouds/json/internal/DeserializationConstructorAndReflectiveTypeAdapterFactory.java
Changelog:
https://github.com/google/gson/blob/master/CHANGELOG.md
> JCLOUDS-1160: Upgrade to Gson 2.7

- providers/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/compute/config/GoogleComputeEngineServiceContextModule.java
- providers/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/domain/Instance.java
- providers/google-compute-engine/src/test/java/org/jclouds/googlecomputeengine/compute/GoogleComputeEngineServiceLiveTest.java
- providers/google-compute-engine/src/test/java/org/jclouds/googlecomputeengine/compute/functions/InstanceToNodeMetadataTest.java
- providers/google-compute-engine/src/test/java/org/jclouds/googlecomputeengine/features/InstanceApiLiveTest.java
- providers/google-compute-engine/src/test/java/org/jclouds/googlecomputeengine/features/InstanceApiWindowsLiveTest.java
- providers/google-compute-engine/src/test/java/org/jclouds/googlecomputeengine/features/TargetPoolApiLiveTest.java
This fixes all live tests except one. We're close to having all green!
> GCE live test fixes

- apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStore.java
- apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/blobstore/RegionScopedSwiftBlobStoreParallelLiveTest.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
Clients use this during `completeMultipartUpload`.
> Include part size in listMultipartUpload result

- core/src/main/java/org/jclouds/suppliers/SupplyKeyMatchingValueOrNull.java
- core/src/test/java/org/jclouds/suppliers/SupplyKeyMatchingValueOrNullTest.java
https://issues.apache.org/jira/browse/JCLOUDS-1227
> JCLOUDS-1227: Allow to configure regions with the same URI

- providers/azureblob/src/main/java/org/jclouds/azureblob/domain/ContainerProperties.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/domain/MutableContainerPropertiesWithMetadata.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/domain/PublicAccess.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/domain/internal/ContainerPropertiesImpl.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/domain/internal/MutableContainerPropertiesWithMetadataImpl.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/functions/ParseContainerPropertiesFromHeaders.java
- providers/azureblob/src/main/java/org/jclouds/azureblob/xml/AccountNameEnumerationResultsHandler.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientLiveTest.java
- providers/azureblob/src/test/java/org/jclouds/azureblob/xml/AccountNameEnumerationResultsHandlerTest.java
- providers/azureblob/src/test/resources/test_list_containers.xml
- providers/azureblob/src/test/resources/test_list_containers_options.xml
REST API version 2016-05-31 includes PublicAccess in List Containers
and Get Container Properties APIs.
> JCLOUDS-1228: Include PublicAccess in responses

- apis/docker/src/main/java/org/jclouds/docker/domain/NetworkSettings.java
- project/pom.xml
- providers/profitbricks/src/main/java/org/jclouds/profitbricks/domain/Firewall.java
This resolves issues using Java 9.  Release notes:
https://github.com/google/auto/releases/tag/auto-value-1.4-rc2
> JCLOUDS-1101: Upgrade to auto-value 1.4-rc2

- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/compute/extensions/AWSEC2SecurityGroupExtension.java
Splitting the amazon changes from https://github.com/jclouds/jclouds/pull/1111 into this PR to make it easier to merge.
I've already tested these changes.
> JCLOUDS-1307: aws-ec2: Invalidate SG on removal even if already externally deleted

- apis/chef/src/main/java/org/jclouds/ohai/config/OhaiModule.java
- apis/ec2/src/test/java/org/jclouds/ec2/internal/BaseEC2ApiExpectTest.java
- apis/openstack-nova-ec2/src/test/java/org/jclouds/openstack/nova/ec2/internal/BaseNovaEC2RestApiExpectTest.java
> Address BindingToUnqualifiedCommonType warnings

- apis/ec2/src/test/java/org/jclouds/ec2/compute/strategy/CreateKeyPairAndSecurityGroupsAsNeededAndReturnRunOptionsTest.java
- project/pom.xml
- providers/aws-ec2/src/test/java/org/jclouds/aws/ec2/compute/strategy/CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptionsTest.java
Also switch from unmaintained easymockclassextension to easymock.
Release notes:
https://github.com/easymock/easymock/releases
> Upgrade to EasyMock 3.4

- apis/s3/src/main/java/org/jclouds/s3/domain/CannedAccessPolicy.java
Also use CaseFormat instead of extra logic.
> JCLOUDS-1370: Add CannedAccessPolicy constants

- apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
- apis/filesystem/src/test/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImplTest.java
> Handle "file" and "file/" collision

- apis/sts/src/main/java/org/jclouds/aws/domain/Region.java
- providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/AWSEC2ProviderMetadata.java
- providers/aws-ec2/src/test/java/org/jclouds/aws/ec2/compute/AWSEC2TemplateBuilderLiveTest.java
- providers/aws-s3/src/main/java/org/jclouds/aws/s3/AWSS3ProviderMetadata.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/integration/AWSS3ServiceIntegrationLiveTest.java
https://issues.apache.org/jira/browse/JCLOUDS-1373
> JCLOUDS-1373: Add eu-west-3 (Paris) AWS region

- providers/google-compute-engine/src/test/java/org/jclouds/googlecomputeengine/compute/loaders/DiskURIToImageTest.java
Add missing unit tests as requested: https://github.com/jclouds/jclouds/pull/1179
> JCLOUDS-1381: Add unit tests

- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
Previously filesystem and transient returned `ByteSource` while all
other providers returned `InputStream`.
> JCLOUDS-1367: Return InputStream from getBlob

- apis/s3/src/main/java/org/jclouds/s3/domain/ObjectMetadata.java
- providers/aws-s3/src/test/java/org/jclouds/aws/s3/AWSS3ClientLiveTest.java
Also improve test coverage of storage classes.
> JCLOUDS-1399: Support S3 One Zone-IA storage class

- project/pom.xml
animal sniffer 1.14 gives compatibility with Java 8.
> JCLOUDS-1333: Upgrade animal sniffer to 1.16

- providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/blobstore/GoogleCloudStorageBlobStore.java
This aligns that the destination's storageClass with that of the sub-object(s) being composed
> JCLOUDS-1389: When composing, set destination.storageClass from object

- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/functions/VirtualMachineToStatus.java
- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/VirtualMachineInstance.java
- providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/compute/functions/VirtualMachineToStatusTest.java
https://issues.apache.org/jira/browse/JCLOUDS-1418
> JCLOUDS-1418: Add missing PowerState values

- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/AzureComputeApi.java
- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/AzureComputeProviderMetadata.java
- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/LocalNetworkGateway.java
- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/LocalNetworkGatewayProperties.java
- providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/features/LocalNetworkGatewayApi.java
- providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/AvailabilitySetApiMockTest.java
- providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/LocalNetworkGatewayApiLiveTest.java
- providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/LocalNetworkGatewayApiMockTest.java
- providers/azurecompute-arm/src/test/resources/localnetworkgatewaycreate.json
- providers/azurecompute-arm/src/test/resources/localnetworkgatewayget.json
- providers/azurecompute-arm/src/test/resources/localnetworkgatewaylist.json
This PR adds the Local Gateway Network API and is the first of a set of PRs that will add support for configuring VPNs in Azure ARM: https://docs.microsoft.com/en-us/rest/api/network-gateway/
> Added Local Network Gateway API

- apis/filesystem/src/test/java/org/jclouds/filesystem/integration/FilesystemBlobIntegrationTest.java
- blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
Previously the filesystem provider could exhaust file descriptors by
eagerly opening up to 10,000 parts.  This partially undoes
JCLOUDS-1367.
> Lazily open InputStream during complete MPU

- project/pom.xml
Addresses an error while building Javadoc.
> Remove JavaScript from footer

- core/pom.xml
- core/src/main/java/org/jclouds/functions/ExpandProperties.java
- project/pom.xml
- resources/modernizer_exclusions.txt
- scriptbuilder/pom.xml
- scriptbuilder/src/main/java/org/jclouds/scriptbuilder/functionloader/osgi/BundleFunctionLoader.java
Notably this adds support for inline suppressions.  Release notes:
https://github.com/gaul/modernizer-maven-plugin/releases
> Upgrade to modernizer-maven-plugin 1.8.0
